### ISSUE TITLE
Contoh kirim pesan dengan REST API 

### ISSUE THREAD

**Issue by mdestafadilah** [taufikdev88/simplewhatsappapi#17]
Ada sample nyah pak? kok saya bingung ya. mksh pak

**Comment by taufikdev88** [comment]
apa yang dibingungkan ya gan ?

**Comment by mdestafadilah** [comment]
> apa yang dibingungkan ya gan ?

endpointnya pak, langkah langkahya, sampe bisa kirim wa by api yang pak taufik buat

**Comment by taufikdev88** [comment]
seperti yang di youtube saya gan, dijalankan sebagai container dengan port yang dibuka lalu bisa di akses web nya dan dimunculkan qr nya untuk discan memakai aplikasi whatsapp

**Comment by mdestafadilah** [comment]
> seperti yang di youtube saya gan, dijalankan sebagai container dengan port yang dibuka lalu bisa di akses web nya dan dimunculkan qr nya untuk discan memakai aplikasi whatsapp

ouh udah pernah di share di yutube, link yuutubenya pak. mksh

--
udah dapet pak link youtubenya. mksh pak.
