### ISSUE TITLE
API GET

### ISSUE THREAD

**Issue by tuyewxx** [taufikdev88/simplewhatsappapi#18]
Bang Taufik mau tanya, apakah bisa dengan metode get seperti 
http://ip:8084/message?phoneNumber=[628xxxxxx]&message=[text]

apakah harus menambahkan key atau session??

**Comment by taufikdev88** [comment]
Sekarang ini belum bisa, kalaupun dibutuhkan untuk mengirim melalui path query, tetap method yang dipakai POST bang

**Comment by tuyewxx** [comment]
> Sekarang ini belum bisa, kalaupun dibutuhkan untuk mengirim melalui path query, tetap method yang dipakai POST bang

nambahin nya di file yang mana bang,
dan seperti apa variable nya?

soalnya butuh integrasi dengan kode [number] dan [text]

**Comment by taufikdev88** [comment]
Bisa di tambah di file src/controllers/message.ts, catatan: GET /message sudah ada implementasi nya untuk menampilkan view html

Mungkin bisa pake path baru yg ingin di custom sendiri

Jangan lupa daftarkan juga route nya di file src/app.ts
