### ISSUE TITLE
Tambah fitur

### ISSUE THREAD

**Issue by doko89** [taufikdev88/simplewhatsappapi#5]
Mas bisa request tambah fitur ga, untuk kirim pesan ke group wa. Sama support docker di arsitektur arm biar bs jalan di raspberry. Thanks

**Comment by irfnrdh** [comment]
+ fitur token untuk production :smile:

**Comment by taufikdev88** [comment]
> * fitur token untuk production 😄

wah jadi gak simple lagi dong 😄

**Comment by irfnrdh** [comment]
support arm dulu deh :+1:

**Comment by tuyewxx** [comment]
> Mas bisa request tambah fitur ga, untuk kirim pesan ke group wa. Sama support docker di arsitektur arm biar bs jalan di raspberry. Thanks

saya bisa di armbian stb lagi..:)
