### ISSUE TITLE
sering crash

### ISSUE THREAD

**Issue by doko89** [taufikdev88/simplewhatsappapi#6]
errornya biasanya terjadi kalo lama idle trus kirim pesan bisa ampe 3x crash,, setelah coba kirim pesan ke 4x baru jalan. error nya kayak gini

> Formatted jid to: 6285xxxxxxxxxx@s.whatsapp.net
> /app/services/WhatsappService.js:114
>             yield this.sock.presenceSubscribe(jid);
>                             ^
> 
> TypeError: this.sock.presenceSubscribe is not a function
>     at WhatsappService.<anonymous> (/app/services/WhatsappService.js:114:29)
>     at Generator.next (<anonymous>)
>     at /app/services/WhatsappService.js:31:71
>     at new Promise (<anonymous>)
>     at __awaiter (/app/services/WhatsappService.js:27:12)
>     at WhatsappService.SendWhatsappSimpleMessage (/app/services/WhatsappService.js:110:16)
>     at /app/index.js:56:16
>     at /app/helper/Validator.js:10:29
>     at AsyncResolvers.resolvedAll [as onResolvedAll] (/app/node_modules/validatorjs/src/validator.js:103:9)
>     at AsyncResolvers.fire (/app/node_modules/validatorjs/src/async.js:65:12)
> Example app listening at http://0.0.0.0:80

**Comment by taufikdev88** [comment]
apakah aplikasi whatsapp nya sudah terbaru ?

**Comment by doko89** [comment]
Iya mas yg terbaru

**Comment by mdestafadilah** [comment]
apakah ada info terbaru?

**Comment by taufikdev88** [comment]
ada update di versi 2.0.2
