### ISSUE TITLE
Error logout

### ISSUE THREAD

**Issue by ahmadi330040** [taufikdev88/simplewhatsappapi#7]
Ini kenapa yah?
![image](https://user-images.githubusercontent.com/67589784/206623688-19639b5c-e872-466e-8e89-2aafb3b090c3.png)

**Comment by ahmadi330040** [comment]
Eror nya ketika dari device sudah logout duluan, baru hit api /logout

**Comment by taufikdev88** [comment]
api /logout sudah dihilangkan di versi 2.0.2 biar tidak terjadi conflict
